baseurl = "https://philipzakarian.com"
languageCode = "en-us"
title = "Ֆիլիբ Զաքարեան"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
rssLimit = 20
summaryLength = 25

[taxonomies]
  hador = "hadorner"

[markup]
  [markup.highlight]
    style="native"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.feed]]
    weight = 1
    name = "rss"
    url = "/index.xml"

[[menu.feed]]
    weight = 3
    name = "մեր մասին"
    url = "/page/contact"

[[menu.feed]]
    weight = 2
    name = "կապ"
    url = "mailto:contact@philipzakarian.com"

[[menu.feed]]
    weight = 4
    name = "գիրքեր"
    url = "/page/books"

#[[menu.feed]]
#    name = "կենսագրական"
#    url = "/page/bio"

#[[menu.feed]]
#    name = "հատորներ"
#    url = "/hadorner/"

[params]
    footer = ""
    poweredby = ""
    subtitle = "Որբը Տուն Շինեց"
    logo = "images/logo.png"
    favicon = "favicon.ico"
    commit = false
    rss = true
    comments = false
    og_image = "/images/logo.png"

[author]
    name = "Ֆիլիբ Զաքարեան"

[markup.goldmark.renderer]
    unsafe= true
